plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/jeffreywylie/agio-protocol/landing-page"
publishOrigin = "default"
base = "/Users/jeffreywylie/agio-protocol/landing-page"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "no-cache, must-revalidate"

[[headers]]
for = "/nav.js"

[headers.values]
Cache-Control = "no-cache, must-revalidate"

[[headers]]
for = "/.well-known/*"

[headers.values]
Cache-Control = "public, max-age=3600"
Access-Control-Allow-Origin = "*"