[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_vault = "68RkssMLwfAWZ3Hf8TGF6poACgvo7ePPA8BzThqoMp6y"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
